// app/us-stocks/[symbol]/page.tsx
import StockChart from "@/components/StockChart";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import Link from "next/link";

type Props = {
  params: Promise<{ symbol: string }>;
};

export default async function StockDetailPage(props: Props) {
  const params = await props.params;
  const symbol = params.symbol.toUpperCase();

  // The real data is now being fetched dynamically inside <StockChart />
  const chartData: any[] = [];

  return (
    <div className="page-wrapper">
      <div className="page-content">
        <br />
        <Breadcrumb>
          <BreadcrumbList className="justify-center">
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="/">Main Menu</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="/us-stocks">US Stocks</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>{symbol}</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>

        <h1 style={{ margin: "20px 0", color: "#fff" }}>
          {symbol} Stock Price
        </h1>

        <StockChart
          data={chartData}
          xAxisKey="time"
          yAxisKey="price"
          symbol={symbol}
        />

        <div className="bg-white p-8 rounded-3xl border border-zinc-200 shadow-[0_2px_10px_-3px_rgba(6,81,237,0.05)] flex flex-col hover:border-[#061c26]/30 transition-colors mt-12">
          <h3 className="text-xl font-bold text-zinc-900">
            FinSense Prediction
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm flex-grow">
            This is a place holder for prediction text that will be generated by
            the FinSense AI model in the future.
          </p>
        </div>
      </div>
    </div>
  );
}
